name: caso2
services:
  back:
    image: back
    container_name: back
    build:
      context: ./back
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./back:/back
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  front:
    image: front
    container_name: front
    build:
      context: ./front
    command: sh -c "npm install && npm start"
    volumes:
      - ./front/:/front
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nombre_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3306:3306"
    volumes:
      - ./base/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./proxy/myconf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    depends_on:
      - front
      - back
