CREATE TABLE IF NOT EXISTS ciudadano (
  id_cc CHAR(8) PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  nombres VARCHAR(50) NOT NULL,
  apellidos VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  pass VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE
);